<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nasreen">
<meta name="dcterms.date" content="2026-08-30">

<title>Elementary options strategies – nasreen-ahmed.github.io</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3351eac5b0d0e5f1e99acc15048a755f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;800&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');
</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">nasreen-ahmed.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Elementary options strategies</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                                <div class="quarto-categories">
                <div class="quarto-category">Options</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Nasreen </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 30, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#simple-buy-and-sell-strategies" id="toc-simple-buy-and-sell-strategies" class="nav-link active" data-scroll-target="#simple-buy-and-sell-strategies">Simple buy and sell strategies</a></li>
  <li><a href="#riskreward-characteristics" id="toc-riskreward-characteristics" class="nav-link" data-scroll-target="#riskreward-characteristics">Risk/Reward Characteristics</a></li>
  <li><a href="#combination-strategies" id="toc-combination-strategies" class="nav-link" data-scroll-target="#combination-strategies">Combination Strategies</a></li>
  <li><a href="#constructing-an-expiration-graph" id="toc-constructing-an-expiration-graph" class="nav-link" data-scroll-target="#constructing-an-expiration-graph">Constructing An Expiration Graph</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>How might a beginning trader assess an option’s value? One simple method depends on guessing where the underlying contract will be at expiration. If an option position is held to expiration, the option will be worth either zero, if it is at- or out-of-the-money, or intrinsic value, if its in-the-money.</p>
<p><em>The purchase of an option will be profitable if its trade price is less than its value at expiration. The sale of an option will be profitable if its trade price is greater than its value at expiration.</em></p>
<section id="simple-buy-and-sell-strategies" class="level2">
<h2 class="anchored" data-anchor-id="simple-buy-and-sell-strategies">Simple buy and sell strategies</h2>
<p>For example, suppose the following options are available with two months remaining to expiration, and the underlying contract trading at 99.00:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Stock Price</th>
<th>85</th>
<th>90</th>
<th>95</th>
<th>100</th>
<th>105</th>
<th>110</th>
<th>115</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Call</td>
<td>14.05</td>
<td>9.35</td>
<td>5.50</td>
<td>2.70</td>
<td>1.15</td>
<td>0.45</td>
<td>0.20</td>
</tr>
<tr class="even">
<td>Put</td>
<td>0.10</td>
<td>0.45</td>
<td>1.55</td>
<td>3.70</td>
<td>7.10</td>
<td>11.35</td>
<td>16.10</td>
</tr>
</tbody>
</table>
<p>Suppose we believe that the underlying contract will rise to at least 108 by expiration. We might want to purchase a 100 call for 2.70. If we are correct, and the contract does in fact end at 108, our profilt at expiration will be the option’s intrinsic value of 8.00 less the 2.70 we originally paid , or 5.30 .</p>
<p>Given the above prices, if the underlying market rises to 108 by expiration we will show a profit if we purchase any call with an exercise price less than 110. <strong>The intrinsic value of each of these options at expiration will be greater than its current price in the marketplace</strong>.</p>
<p>What about the 110 and 115 calls ? If one believes that 108.00 is a reasonable upside goal for the underlying contract, but consider it unlikely that the price will rise above 110, then it will be preferable to be sellters of the 110 and 115 calls.</p>
<p>If one sell the 110 call for 0.45 and the underlying contract never rises above 110.00, the 110 call will expire and the seller of the option will get to keep the full premium of 0.45. One can also sell 115 call for 0.20 , giving an additional 5 point margin of error. If the underlying contract never rises about 115.00, the 115 call will expire worthless and the seller of the call option will get to keep the full premium of 0.20.</p>
<p>Using the same approach one can assess the potential profile from the purchase or sale of a put. As with a call, a put’s intrinsic value at expiration must be greater than its trade price in order for the purchase of a put to be profitable.</p>
<p>If the underlying contract rises to 108.00 by expiration, any put with an exercise price of 105 or less will be worthless. If one sells any of these pu, they will profilt by the full amount of the premium. If one sell the 110 or 115 puts, they will not be totally worthless at expiration because with the underlying contract at 108.00, they will have intrinsic values of 2.00 and 7.00 respectively. However, it will still be less than their trade price of 11.35 and 16.10.</p>
<p>As one changes, the assumptions about the likely price of the underlying contract at expiration, that will alter the likely profit or loss from any option position.</p>
<p>If , instead of rising to 108.00 , the underlying contract actually rises to 120.00 , the purchase of the 100 call for 2.70 will result in a profit of 17.30 rather than 5.30. On the other hand, if the underlying contract falls to 90.00, the purchase of the 100 call will result in the loss of the full premium 2.70. In the latter case, if we sell the 110 put for 11.35, instead of making 9.35 as we would with the underlying contract at 108.00,we will actually loss 8.65.</p>
<p>Profit and Loss Graph of an underlying contract</p>
<div id="a5f61428" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Long an underlying contract at 99 </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">99</span>  <span class="co"># Original buy price</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>profit_loss_long <span class="op">=</span> S_t <span class="op">-</span> K</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting the long on underlying contract at 99 </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss_long,label <span class="op">=</span> <span class="st">'Long an underlying contract at 99'</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Short an underlying contract at 99 </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>profit_loss_short <span class="op">=</span>  K <span class="op">-</span> S_t</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss_short,label <span class="op">=</span><span class="st">'Short an underlying contract at 99'</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>))</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Expiration of Long and Short Position at 99"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">"upper center"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-2-output-1.png" width="578" height="432" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The figure show the value at expiration of both a long and a short position in our example underlying contract taken at the current price of 99.00 - The horizontal(x) axis represents the price of the underlying futures contact, and the vertical (y) axis represents the profit or loss from our position. - The potential profit or loss to each position is therefore unlimited. - Also note that there is a continuous one-to-one relationship between movement in the underlying contract and the value of the position. If we take a long position , for each point the underlying contract rises, we make a point , for each point the underlying contract falls, we lose a point. If we take a short position the situation is just reversed. For each point the underlying contract rises, we lose a point, for each point the underlying contract falls, we make a point.</p>
<p>Using the same evaluation method, the next figure show the profit or loss at expiration from the purchase of a 100 call at 2.70. The graph is no longer a straight line.</p>
<p>Above 100, the call will be <strong>in-the-money</strong>, and will increase in value at the same rate as the underling contract; the position will gain one point in value for each point rise in the value of the underlying contract.</p>
<p>If the underlying contract finishes at 102.70 the 100 call, will be worth its intrinsic value of 2.70, and break exactly even.</p>
<p>Above 102.70, the profile from the purchase of the 100 call is potentially unlimited, just take a long position in the underlying contract.</p>
<div id="8313e6c5" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">100</span>  <span class="co"># Exercise Price</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">110</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#for i in S_t:</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#    if i &lt; K :</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#        # Here the call option will not be #exercised</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">#        value = - call_option_premium</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#    elif i &gt;= K:</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">#        # Here the call option will be #exercised </span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">#        value = (i - K) - #call_option_premium</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">#    </span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">#    profit_loss.append(value)</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [np.maximum([i <span class="op">-</span> K], <span class="dv">0</span>) <span class="op">-</span> call_option_price <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'long a 100 call at 2.70'</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Profit or Loss at expiration from the purchase of a 100 call at 2.70"</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>plt.grid()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-1.png" width="573" height="432" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="riskreward-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="riskreward-characteristics">Risk/Reward Characteristics</h2>
<p>The profit and loss graph of a long call position at expiration will always have the same general shape as the above graph. The position will have <strong>limited downside risk and unlimited upside profit potential</strong>.</p>
<p>The exact point at which the maximum loss will occur is determined by the exercise price ( the point at which the graph bends) and the price of the option.</p>
<p>Below is a graph of long positions in the 95, 100 and 105 calls</p>
<div id="696670ff" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (strike, premium, color) <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span> np.maximum(S_t <span class="op">-</span> strike, <span class="dv">0</span>) <span class="op">-</span> premium</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'long a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> call at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" width="582" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The below graph represents the profit and loss from a short position in the 95, 100 and 105 calls. The positions now have profit potential limited to the amount of the premium for which they were sold , and unlimited upside risk similar to a short position in the underlying contract.</p>
<div id="4b1e695b" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace (<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> strike, premium, color <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span>  premium <span class="op">-</span> np.maximum(S_t  <span class="op">-</span> strike,<span class="dv">0</span>) </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'short a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> call at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" width="591" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The below figure represents long positions in the 95,100 and 105 put. The risk/reward characteristics of these positions are similar to long call positions, but now the limited risk is on the upside and the unlimited profit potential is on the downside. The position will break even if the underlying contract falls below the exercise price by exactly the amount of the option’s trade price.</p>
<div id="a6e6eeeb" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace (<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> strike, premium, color <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span> np.maximum( strike <span class="op">-</span> S_t, <span class="dv">0</span>) <span class="op">-</span> premium</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'long a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> put at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="569" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The below graph are the short put positions. Each position has upside profit potential limited to the amount of the trade price , and a potential unlimited loss similar to a long position in the underlying contract.</p>
<div id="a7865b89" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace (<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> strike, premium, color <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span> premium <span class="op">-</span> np.maximum( strike <span class="op">-</span> S_t, <span class="dv">0</span>) </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'short a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> put at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-1.png" width="578" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The immediate above 4 plots illustrates two of the most important characteristics of options : Buyers of options have limited risk and potentially unlimited reqard ; sellers of options have limited reward and potentially unlimited risk.</p>
<p>More specifically, <strong>net buyers(sellers) of calls have unlimited upside reward (risk) , and net buyers(sellers) of puts have unlimited downward reward (risk)</strong>.</p>
<p>Option traders learn that the limited or unlimited risk/reward characteristics of a trade are not the only considerations. Atleast as important is the probability of that unlimited profit or loss. As an example, suppose a trader is considering a trade which has only two possible outcomes. In one case the trader will double his money; in the other case he will go broke. In may seem that a rational trader will avoid such a trade because the reward does not appear to justify the risk. But suppose the probability of the second outcome is only one chance in a million. In addition to the potential risk and reward associated with any trade, a trader must also consider the likelihood of the various outcomes.</p>
</section>
<section id="combination-strategies" class="level2">
<h2 class="anchored" data-anchor-id="combination-strategies">Combination Strategies</h2>
<p>Combine option positions to form new options. The below graph shows the profit and loss at expiration from the combined purchase of a 100 call for 2.70 and a 100 put for 3.70. Here a total of 6.40 was paid, which will be the maximum loss if both option expire worthless. This will happen is the underlying contract is right at 100 at expiration. If the underlying contract is above 100 at expiration the put will be worthless, but the call will act like a long underlying position, gaining one point in value for each point the underlying contract rises. If the underlying contract is below 100 the call will be worthless, but the put will act like a short underlying position, gaining one point in value for each point the underlying contract falls.</p>
<p>In order for the position to do no worse than break even, it must be worth at least the 6.40 we originally paid. This will occur if either the 100 call or 100 put turns out to be worth 6.40. At expiration, the underlying contract must be at or above 106.40 or at or below 93.60. Outside this range, the potential profits is unlimited.</p>
<div id="9f6593fd" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">100</span>  <span class="co"># Exercise Price</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>put_option_price <span class="op">=</span> <span class="fl">3.70</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [np.maximum([i <span class="op">-</span> K], <span class="dv">0</span>) <span class="op">+</span>np.maximum([K<span class="op">-</span>i],<span class="dv">0</span>) <span class="op">-</span> call_option_price <span class="op">-</span> put_option_price <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'long a 100 call at 2.70 </span><span class="ch">\n</span><span class="st"> long a 100 put at 3.70'</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>plt.grid()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-1.png" width="569" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Under what conditions might we initiate the position as shown above.?</p>
<p>Such a position might be sensible if one thought a large move in the underlying contract would take place in the near future, but were uncertain as to the direction of that move.</p>
<p>One might also take the opposite view, that the underlying contract was unlikely to either fall below 93.60 or rise above 106.40. Under these conditions we might prefer to sell both the 100 call and 100 put , which our risk in either direction is unlimited.</p>
<div id="fa4ded5f" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">100</span>  <span class="co"># Exercise Price</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>put_option_price <span class="op">=</span> <span class="fl">3.70</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [ call_option_price <span class="op">+</span> put_option_price <span class="op">-</span> np.maximum([i <span class="op">-</span> K], <span class="dv">0</span>)  <span class="op">-</span> np.maximum([K<span class="op">-</span>i],<span class="dv">0</span>) <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'short a 100 call at 2.70 </span><span class="ch">\n</span><span class="st">short a 100 put at 3.70'</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>plt.grid()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="569" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Suppose we take a view similar to the above figure, that the underlying contract is unlikely to make a big move in either direction. But because there is always a chance, one could go wrong, one might want to increase the margin of error by increasing our range of profitability beyong 93.60-106.40 range.</p>
<p>So, instead of selling a 100 call and a 100 put, one might sell a 95 put for 1.55 and a 105 call for 1.15. This position will realise a maximum profit of 2.70 within the range 95-105, where both options will expire worthless. The seller wont lose money unless the underling contract finishes below 92.30 or above 107.70 at expiration .</p>
<div id="f105b7f2" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>call_strike <span class="op">=</span> <span class="dv">105</span>  <span class="co"># Exercise Price</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>put_strike <span class="op">=</span> <span class="dv">95</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">1.15</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>put_option_price <span class="op">=</span> <span class="fl">1.15</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [ call_option_price <span class="op">+</span> put_option_price <span class="op">-</span> np.maximum([i <span class="op">-</span> call_strike], <span class="dv">0</span>)  <span class="op">-</span> np.maximum([put_strike <span class="op">-</span> i],<span class="dv">0</span>) <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'short a 95 put at 1.15 </span><span class="ch">\n</span><span class="st">short a 105 call at 1.15'</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>plt.grid()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" width="569" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The maximum profit now is 3.70 and in the earlier case it was 6.40. In return for a reduced risk, one must be satisfied with a reduced profit potential.</p>
<p>The position in the immediate above 3 graphs all have either unlimited reward or unlimited risk because they are either net long or net short options.</p>
<p>Purchasing and selling equal number of options of the same type, one can create positions which have limited risk and unlimited reward.</p>
<p>For example, buy a 90 call for 9.35 and sell a 100 call for 2.70 for a total debit of 6.65.</p>
<div id="75e5dde5" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>long_call <span class="op">=</span> <span class="dv">90</span>  <span class="co"># Exercise Price</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>short_call <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>long_call_premium <span class="op">=</span> <span class="fl">9.35</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>short_call_premium <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [ np.maximum([i <span class="op">-</span> long_call], <span class="dv">0</span>) <span class="op">-</span> </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    long_call_premium <span class="op">+</span> short_call_premium <span class="op">-</span> np.maximum([i <span class="op">-</span> short_call], <span class="dv">0</span>)  <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'long a 90 call at 9.35 </span><span class="ch">\n</span><span class="st">short a 100 call at 2.70'</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>plt.grid()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" width="569" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="constructing-an-expiration-graph" class="level2">
<h2 class="anchored" data-anchor-id="constructing-an-expiration-graph">Constructing An Expiration Graph</h2>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ul>
<li><em>Option Pricing and Volatility - Advanced Strategies And Trading Techniques - Sheldon Natenberg.</em></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("http:\/\/nasreen-ahmed\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Elementary options strategies"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Nasreen"</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-08-30"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [Options]</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># image: "image.jpg"</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc-depth:</span><span class="co"> 3</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="an">jupyter:</span><span class="co"> python3</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span><span class="co"> </span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">  enabled: true</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>How might a beginning trader assess an option's value? One simple method depends on guessing where the underlying contract will be at expiration. If an option position is held to expiration, the option will be worth either zero, if it is at- or out-of-the-money, or intrinsic value, if its in-the-money. </span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>*The purchase of an option will be profitable if its trade price is less than its value at expiration. The sale of an option will be profitable if its trade price is greater than its value at expiration.*</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Simple buy and sell strategies</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>For example, suppose the following options are available with two months remaining to expiration, and the underlying contract trading at 99.00:</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Stock Price <span class="pp">|</span>   85   <span class="pp">|</span>  90   <span class="pp">|</span>  95   <span class="pp">|</span>  100  <span class="pp">|</span>  105  <span class="pp">|</span>  110  <span class="pp">|</span>  115   <span class="pp">|</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------------|-------</span> <span class="pp">|-------|-------|-------|-------|--------|-------|</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Call        <span class="pp">|</span> 14.05  <span class="pp">|</span> 9.35  <span class="pp">|</span> 5.50  <span class="pp">|</span> 2.70  <span class="pp">|</span> 1.15  <span class="pp">|</span> 0.45   <span class="pp">|</span> 0.20  <span class="pp">|</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Put         <span class="pp">|</span> 0.10   <span class="pp">|</span> 0.45  <span class="pp">|</span> 1.55  <span class="pp">|</span> 3.70  <span class="pp">|</span> 7.10  <span class="pp">|</span> 11.35  <span class="pp">|</span> 16.10 <span class="pp">|</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>Suppose we believe that the underlying contract will rise to at least 108 by expiration. We might want to purchase a 100 call for 2.70. </span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>If we are correct, and the contract does in fact end at 108, our profilt at expiration will be the option's intrinsic value of 8.00 less the 2.70 we originally paid , or 5.30 . </span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>Given the above prices, if the underlying market rises to 108 by expiration we will show a profit if we purchase any call with an exercise price less than 110. **The intrinsic value of each of these options at expiration will be greater than its current price in the marketplace**.</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>What about the 110 and 115 calls ? If one believes that 108.00 is a reasonable upside goal for the underlying contract, but consider it unlikely that the price will rise above 110, then it will be preferable to be sellters of the 110 and 115 calls. </span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>If one sell the 110 call for 0.45 and the underlying contract never rises above 110.00, the 110 call will expire and the seller of the option will get to keep the full premium of 0.45. </span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>One can also sell 115 call for 0.20 , giving an additional 5 point margin of error. If the underlying contract never rises about 115.00, the 115 call will expire worthless and the seller of the call option will get to keep the full premium of 0.20. </span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>Using the same approach one can assess the potential profile from the purchase or sale of a put. As with a call, a put's intrinsic value at expiration must be greater than its trade price in order for the purchase of a put to be profitable. </span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>If the underlying contract rises to 108.00 by expiration, any put with an exercise price of 105 or less will be worthless. If one sells any of these pu, they will profilt by the full amount of the premium. </span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>If one sell the 110 or 115 puts, they will not be totally worthless at expiration because with the underlying contract at 108.00, they will have intrinsic values of 2.00 and 7.00 respectively. </span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>However, it will still be less than their trade price of 11.35 and 16.10. </span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>As one changes, the assumptions about the likely price of the underlying contract at expiration, that will alter the likely profit or loss from any option position. </span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>If , instead of rising to 108.00 , the underlying contract actually rises to 120.00 , the purchase of the 100 call for 2.70 will result in a profit of 17.30 rather than 5.30. </span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>On the other hand, if the underlying contract falls to 90.00, the purchase of the 100 call will result in the loss of the full premium 2.70. In the latter case, if we sell the 110 put for 11.35, instead of making 9.35 as we would with the underlying contract at 108.00,we will actually loss 8.65.</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>Profit and Loss Graph of an underlying contract</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Long an underlying contract at 99 </span></span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">99</span>  <span class="co"># Original buy price</span></span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>profit_loss_long <span class="op">=</span> S_t <span class="op">-</span> K</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting the long on underlying contract at 99 </span></span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss_long,label <span class="op">=</span> <span class="st">'Long an underlying contract at 99'</span>)</span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a><span class="co"># Short an underlying contract at 99 </span></span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a>profit_loss_short <span class="op">=</span>  K <span class="op">-</span> S_t</span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss_short,label <span class="op">=</span><span class="st">'Short an underlying contract at 99'</span>)</span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>))</span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Expiration of Long and Short Position at 99"</span>)</span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">"upper center"</span>)</span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a>The figure show the value at expiration of both a long and a short position in our example underlying contract taken at the current price of 99.00 </span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The horizontal(x) axis represents the price of the underlying futures contact, and the vertical (y) axis represents the profit or loss from our position. </span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The potential profit or loss to each position is therefore unlimited. </span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Also note that there is a continuous one-to-one relationship between movement in the underlying contract and the value of the position. If we take a long position , for each point the underlying contract rises, we make a point , for each point the underlying contract falls, we lose a point. </span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a>If we take a short position the situation is just reversed. For each point the underlying contract rises, we lose a point, for each point the underlying contract falls, we make a point. </span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a>Using the same evaluation method, the next figure show the profit or loss at expiration from the purchase of a 100 call at 2.70. The graph is no longer a straight line. </span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a>Above 100, the call will be **in-the-money**, and will increase in value at the same rate as the underling contract; the position will gain one point in value for each point rise in the value of the underlying contract. </span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>If the underlying contract finishes at 102.70 the 100 call, will be worth its intrinsic value of 2.70, and break exactly even. </span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a>Above 102.70, the profile from the purchase of the 100 call is potentially unlimited, just take a long position in the underlying contract.</span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-98"><a href="#cb11-98" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">100</span>  <span class="co"># Exercise Price</span></span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">110</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a><span class="co">#for i in S_t:</span></span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a><span class="co">#    if i &lt; K :</span></span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a><span class="co">#        # Here the call option will not be #exercised</span></span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a><span class="co">#        value = - call_option_premium</span></span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a><span class="co">#    elif i &gt;= K:</span></span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a><span class="co">#        # Here the call option will be #exercised </span></span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a><span class="co">#        value = (i - K) - #call_option_premium</span></span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a><span class="co">#    </span></span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a><span class="co">#    profit_loss.append(value)</span></span>
<span id="cb11-114"><a href="#cb11-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-115"><a href="#cb11-115" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [np.maximum([i <span class="op">-</span> K], <span class="dv">0</span>) <span class="op">-</span> call_option_price <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'long a 100 call at 2.70'</span>)</span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Profit or Loss at expiration from the purchase of a 100 call at 2.70"</span>)</span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a><span class="fu">## Risk/Reward Characteristics</span></span>
<span id="cb11-125"><a href="#cb11-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-126"><a href="#cb11-126" aria-hidden="true" tabindex="-1"></a>The profit and loss graph of a long call position at expiration will always have the same general shape as the above graph. The position will have **limited downside risk and unlimited upside profit potential**. </span>
<span id="cb11-127"><a href="#cb11-127" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb11-128"><a href="#cb11-128" aria-hidden="true" tabindex="-1"></a> The exact point at which the maximum loss will occur is determined by the exercise price ( the point at which the graph bends) and the price of the option. </span>
<span id="cb11-129"><a href="#cb11-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-130"><a href="#cb11-130" aria-hidden="true" tabindex="-1"></a> Below is a graph of long positions in the 95, 100 and 105 calls </span>
<span id="cb11-131"><a href="#cb11-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-134"><a href="#cb11-134" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-135"><a href="#cb11-135" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-136"><a href="#cb11-136" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-137"><a href="#cb11-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-138"><a href="#cb11-138" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb11-139"><a href="#cb11-139" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb11-140"><a href="#cb11-140" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb11-141"><a href="#cb11-141" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb11-142"><a href="#cb11-142" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-143"><a href="#cb11-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-144"><a href="#cb11-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-145"><a href="#cb11-145" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (strike, premium, color) <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb11-146"><a href="#cb11-146" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span> np.maximum(S_t <span class="op">-</span> strike, <span class="dv">0</span>) <span class="op">-</span> premium</span>
<span id="cb11-147"><a href="#cb11-147" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'long a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> call at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb11-148"><a href="#cb11-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-149"><a href="#cb11-149" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-150"><a href="#cb11-150" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-151"><a href="#cb11-151" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-152"><a href="#cb11-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-153"><a href="#cb11-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-154"><a href="#cb11-154" aria-hidden="true" tabindex="-1"></a>The below graph represents the profit and loss from a short position in the 95, 100 and 105 calls. </span>
<span id="cb11-155"><a href="#cb11-155" aria-hidden="true" tabindex="-1"></a>The positions now have profit potential limited to the amount of the premium for which they were sold , and unlimited upside risk similar to a short position in the underlying contract. </span>
<span id="cb11-156"><a href="#cb11-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-159"><a href="#cb11-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-160"><a href="#cb11-160" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb11-161"><a href="#cb11-161" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb11-162"><a href="#cb11-162" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace (<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb11-163"><a href="#cb11-163" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb11-164"><a href="#cb11-164" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-165"><a href="#cb11-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-166"><a href="#cb11-166" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> strike, premium, color <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb11-167"><a href="#cb11-167" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span>  premium <span class="op">-</span> np.maximum(S_t  <span class="op">-</span> strike,<span class="dv">0</span>) </span>
<span id="cb11-168"><a href="#cb11-168" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'short a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> call at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb11-169"><a href="#cb11-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-170"><a href="#cb11-170" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-171"><a href="#cb11-171" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-172"><a href="#cb11-172" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-173"><a href="#cb11-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-174"><a href="#cb11-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-175"><a href="#cb11-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-176"><a href="#cb11-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-177"><a href="#cb11-177" aria-hidden="true" tabindex="-1"></a>The below figure represents long positions in the 95,100 and 105 put.  The risk/reward characteristics of these positions are similar to long call positions, but now the limited risk is on the upside and the unlimited profit potential is on the downside. </span>
<span id="cb11-178"><a href="#cb11-178" aria-hidden="true" tabindex="-1"></a>The position will break even if the underlying contract falls below the exercise price by exactly the amount of the option's trade price. </span>
<span id="cb11-179"><a href="#cb11-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-182"><a href="#cb11-182" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-183"><a href="#cb11-183" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb11-184"><a href="#cb11-184" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb11-185"><a href="#cb11-185" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace (<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb11-186"><a href="#cb11-186" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb11-187"><a href="#cb11-187" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-188"><a href="#cb11-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-189"><a href="#cb11-189" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> strike, premium, color <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb11-190"><a href="#cb11-190" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span> np.maximum( strike <span class="op">-</span> S_t, <span class="dv">0</span>) <span class="op">-</span> premium</span>
<span id="cb11-191"><a href="#cb11-191" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'long a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> put at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb11-192"><a href="#cb11-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-193"><a href="#cb11-193" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-194"><a href="#cb11-194" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-195"><a href="#cb11-195" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-196"><a href="#cb11-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-197"><a href="#cb11-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-198"><a href="#cb11-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-199"><a href="#cb11-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-200"><a href="#cb11-200" aria-hidden="true" tabindex="-1"></a>The below graph are the short put positions. Each position has upside profit potential limited to the amount of  the trade price , and a potential unlimited loss similar to a long position in the underlying contract. </span>
<span id="cb11-201"><a href="#cb11-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-204"><a href="#cb11-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-205"><a href="#cb11-205" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> [<span class="dv">95</span>,<span class="dv">100</span>,<span class="dv">105</span>]</span>
<span id="cb11-206"><a href="#cb11-206" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> [ <span class="fl">5.50</span>, <span class="fl">2.70</span>,<span class="fl">1.15</span>]</span>
<span id="cb11-207"><a href="#cb11-207" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace (<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)</span>
<span id="cb11-208"><a href="#cb11-208" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'orange'</span>, <span class="st">'purple'</span>] </span>
<span id="cb11-209"><a href="#cb11-209" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t, np.linspace(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">50</span>), color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-210"><a href="#cb11-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-211"><a href="#cb11-211" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> strike, premium, color <span class="kw">in</span> <span class="bu">zip</span>(K, call_option_price,colors):</span>
<span id="cb11-212"><a href="#cb11-212" aria-hidden="true" tabindex="-1"></a>    profit_loss <span class="op">=</span> premium <span class="op">-</span> np.maximum( strike <span class="op">-</span> S_t, <span class="dv">0</span>) </span>
<span id="cb11-213"><a href="#cb11-213" aria-hidden="true" tabindex="-1"></a>    plt.plot(S_t, profit_loss, label<span class="op">=</span><span class="ss">f'short a </span><span class="sc">{</span>strike<span class="sc">}</span><span class="ss"> put at </span><span class="sc">{</span>premium<span class="sc">}</span><span class="ss">'</span>,color<span class="op">=</span> color)</span>
<span id="cb11-214"><a href="#cb11-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-215"><a href="#cb11-215" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-216"><a href="#cb11-216" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-217"><a href="#cb11-217" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-218"><a href="#cb11-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-219"><a href="#cb11-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-220"><a href="#cb11-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-221"><a href="#cb11-221" aria-hidden="true" tabindex="-1"></a>The immediate above 4 plots illustrates two of the most important characteristics of options : Buyers of options have limited risk and potentially unlimited reqard ; sellers of options have limited reward and potentially unlimited risk. </span>
<span id="cb11-222"><a href="#cb11-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-223"><a href="#cb11-223" aria-hidden="true" tabindex="-1"></a>More specifically, **net buyers(sellers) of calls have unlimited upside reward (risk) , and net buyers(sellers) of puts have unlimited downward reward (risk)**.</span>
<span id="cb11-224"><a href="#cb11-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-225"><a href="#cb11-225" aria-hidden="true" tabindex="-1"></a>Option traders learn that the limited or unlimited risk/reward characteristics of a trade are not the only considerations. Atleast as important is the probability of that unlimited profit or loss. As an example, suppose a trader is considering a trade which has only two possible outcomes. In one case the trader will double his money; in the other case he will go broke. In may seem that a rational trader will avoid such a trade because the reward does not appear to justify the risk. But suppose the probability of the second outcome is only one chance in a million. </span>
<span id="cb11-226"><a href="#cb11-226" aria-hidden="true" tabindex="-1"></a>In addition to the potential risk and reward associated with any trade, a trader must also consider the likelihood of the various outcomes.  </span>
<span id="cb11-227"><a href="#cb11-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-228"><a href="#cb11-228" aria-hidden="true" tabindex="-1"></a><span class="fu">## Combination Strategies</span></span>
<span id="cb11-229"><a href="#cb11-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-230"><a href="#cb11-230" aria-hidden="true" tabindex="-1"></a>Combine option positions to form new options. The below graph shows the profit and loss at expiration from the combined purchase of a 100 call for 2.70 and a 100 put for 3.70. </span>
<span id="cb11-231"><a href="#cb11-231" aria-hidden="true" tabindex="-1"></a>Here a total of 6.40 was paid, which will be the maximum loss if both option expire worthless. </span>
<span id="cb11-232"><a href="#cb11-232" aria-hidden="true" tabindex="-1"></a>This will happen is the underlying contract is right at 100 at expiration. If the underlying contract is above 100 at expiration the put will be worthless, but the call will act like a long underlying position, gaining one point in value for each point the underlying contract rises. If the underlying contract is below 100 the call will be worthless, but the put will act like a short underlying position, gaining one point in value for each point the underlying contract falls.</span>
<span id="cb11-233"><a href="#cb11-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-234"><a href="#cb11-234" aria-hidden="true" tabindex="-1"></a>In order for the position to do no worse than break even, it must be worth at least the 6.40 we originally paid. This will occur if either the 100 call or 100 put turns out to be worth 6.40. At expiration, the underlying contract must be at or above 106.40 or at or below 93.60. Outside this range, the potential profits is unlimited.</span>
<span id="cb11-235"><a href="#cb11-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-238"><a href="#cb11-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-239"><a href="#cb11-239" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">100</span>  <span class="co"># Exercise Price</span></span>
<span id="cb11-240"><a href="#cb11-240" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb11-241"><a href="#cb11-241" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb11-242"><a href="#cb11-242" aria-hidden="true" tabindex="-1"></a>put_option_price <span class="op">=</span> <span class="fl">3.70</span></span>
<span id="cb11-243"><a href="#cb11-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-244"><a href="#cb11-244" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [np.maximum([i <span class="op">-</span> K], <span class="dv">0</span>) <span class="op">+</span>np.maximum([K<span class="op">-</span>i],<span class="dv">0</span>) <span class="op">-</span> call_option_price <span class="op">-</span> put_option_price <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb11-245"><a href="#cb11-245" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'long a 100 call at 2.70 </span><span class="ch">\n</span><span class="st"> long a 100 put at 3.70'</span>)</span>
<span id="cb11-246"><a href="#cb11-246" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-247"><a href="#cb11-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-248"><a href="#cb11-248" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-249"><a href="#cb11-249" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-250"><a href="#cb11-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-251"><a href="#cb11-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-252"><a href="#cb11-252" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-253"><a href="#cb11-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-254"><a href="#cb11-254" aria-hidden="true" tabindex="-1"></a>Under what conditions might we initiate the position as shown above.? </span>
<span id="cb11-255"><a href="#cb11-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-256"><a href="#cb11-256" aria-hidden="true" tabindex="-1"></a>Such a position might be sensible if one thought a large move in the underlying contract would take place in the near future, but were uncertain as to the direction of that move.</span>
<span id="cb11-257"><a href="#cb11-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-258"><a href="#cb11-258" aria-hidden="true" tabindex="-1"></a>One might also take the opposite view, that the underlying contract was unlikely to either fall below 93.60 or rise above 106.40. Under these conditions we might prefer to sell both the 100 call and 100 put , which our risk in either direction is unlimited. </span>
<span id="cb11-259"><a href="#cb11-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-262"><a href="#cb11-262" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-263"><a href="#cb11-263" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">100</span>  <span class="co"># Exercise Price</span></span>
<span id="cb11-264"><a href="#cb11-264" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb11-265"><a href="#cb11-265" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb11-266"><a href="#cb11-266" aria-hidden="true" tabindex="-1"></a>put_option_price <span class="op">=</span> <span class="fl">3.70</span></span>
<span id="cb11-267"><a href="#cb11-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-268"><a href="#cb11-268" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [ call_option_price <span class="op">+</span> put_option_price <span class="op">-</span> np.maximum([i <span class="op">-</span> K], <span class="dv">0</span>)  <span class="op">-</span> np.maximum([K<span class="op">-</span>i],<span class="dv">0</span>) <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb11-269"><a href="#cb11-269" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'short a 100 call at 2.70 </span><span class="ch">\n</span><span class="st">short a 100 put at 3.70'</span>)</span>
<span id="cb11-270"><a href="#cb11-270" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-271"><a href="#cb11-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-272"><a href="#cb11-272" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-273"><a href="#cb11-273" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-274"><a href="#cb11-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-275"><a href="#cb11-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-276"><a href="#cb11-276" aria-hidden="true" tabindex="-1"></a>Suppose we take a view similar to the above figure, that the underlying contract is unlikely to make a big move in either direction. But because there is always a chance, one could go wrong, one might want to increase the margin of error by increasing our range of profitability beyong 93.60-106.40 range. </span>
<span id="cb11-277"><a href="#cb11-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-278"><a href="#cb11-278" aria-hidden="true" tabindex="-1"></a>So, instead of selling a 100 call and a 100 put, one might sell a 95 put for 1.55 and a 105 call for 1.15. This position will realise a maximum profit of 2.70 within the range 95-105, where both options will expire worthless. The seller wont lose money unless the underling contract finishes below 92.30 or above 107.70 at expiration .</span>
<span id="cb11-279"><a href="#cb11-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-282"><a href="#cb11-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-283"><a href="#cb11-283" aria-hidden="true" tabindex="-1"></a>call_strike <span class="op">=</span> <span class="dv">105</span>  <span class="co"># Exercise Price</span></span>
<span id="cb11-284"><a href="#cb11-284" aria-hidden="true" tabindex="-1"></a>put_strike <span class="op">=</span> <span class="dv">95</span></span>
<span id="cb11-285"><a href="#cb11-285" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb11-286"><a href="#cb11-286" aria-hidden="true" tabindex="-1"></a>call_option_price <span class="op">=</span> <span class="fl">1.15</span></span>
<span id="cb11-287"><a href="#cb11-287" aria-hidden="true" tabindex="-1"></a>put_option_price <span class="op">=</span> <span class="fl">1.15</span></span>
<span id="cb11-288"><a href="#cb11-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-289"><a href="#cb11-289" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [ call_option_price <span class="op">+</span> put_option_price <span class="op">-</span> np.maximum([i <span class="op">-</span> call_strike], <span class="dv">0</span>)  <span class="op">-</span> np.maximum([put_strike <span class="op">-</span> i],<span class="dv">0</span>) <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb11-290"><a href="#cb11-290" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'short a 95 put at 1.15 </span><span class="ch">\n</span><span class="st">short a 105 call at 1.15'</span>)</span>
<span id="cb11-291"><a href="#cb11-291" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-292"><a href="#cb11-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-293"><a href="#cb11-293" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-294"><a href="#cb11-294" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-295"><a href="#cb11-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-296"><a href="#cb11-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-297"><a href="#cb11-297" aria-hidden="true" tabindex="-1"></a>The maximum profit now is 3.70 and in the earlier case it was 6.40. In return for a reduced risk, one must be satisfied with a reduced profit potential. </span>
<span id="cb11-298"><a href="#cb11-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-299"><a href="#cb11-299" aria-hidden="true" tabindex="-1"></a>The position in the immediate above 3 graphs all have either unlimited reward or unlimited risk because they are either net long or net short options. </span>
<span id="cb11-300"><a href="#cb11-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-301"><a href="#cb11-301" aria-hidden="true" tabindex="-1"></a>Purchasing and selling equal number of options of the same type, one can create positions which have limited risk and unlimited reward. </span>
<span id="cb11-302"><a href="#cb11-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-303"><a href="#cb11-303" aria-hidden="true" tabindex="-1"></a>For example, buy a 90 call for 9.35 and sell a 100 call for 2.70 for a total debit of 6.65. </span>
<span id="cb11-304"><a href="#cb11-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-307"><a href="#cb11-307" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb11-308"><a href="#cb11-308" aria-hidden="true" tabindex="-1"></a>long_call <span class="op">=</span> <span class="dv">90</span>  <span class="co"># Exercise Price</span></span>
<span id="cb11-309"><a href="#cb11-309" aria-hidden="true" tabindex="-1"></a>short_call <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb11-310"><a href="#cb11-310" aria-hidden="true" tabindex="-1"></a>S_t <span class="op">=</span> np.linspace(<span class="dv">85</span>,<span class="dv">115</span>,<span class="dv">50</span>)  <span class="co"># Current price</span></span>
<span id="cb11-311"><a href="#cb11-311" aria-hidden="true" tabindex="-1"></a>long_call_premium <span class="op">=</span> <span class="fl">9.35</span></span>
<span id="cb11-312"><a href="#cb11-312" aria-hidden="true" tabindex="-1"></a>short_call_premium <span class="op">=</span> <span class="fl">2.70</span></span>
<span id="cb11-313"><a href="#cb11-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-314"><a href="#cb11-314" aria-hidden="true" tabindex="-1"></a>profit_loss <span class="op">=</span> [ np.maximum([i <span class="op">-</span> long_call], <span class="dv">0</span>) <span class="op">-</span> </span>
<span id="cb11-315"><a href="#cb11-315" aria-hidden="true" tabindex="-1"></a>    long_call_premium <span class="op">+</span> short_call_premium <span class="op">-</span> np.maximum([i <span class="op">-</span> short_call], <span class="dv">0</span>)  <span class="cf">for</span> i <span class="kw">in</span> S_t]</span>
<span id="cb11-316"><a href="#cb11-316" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,profit_loss,label <span class="op">=</span> <span class="st">'long a 90 call at 9.35 </span><span class="ch">\n</span><span class="st">short a 100 call at 2.70'</span>)</span>
<span id="cb11-317"><a href="#cb11-317" aria-hidden="true" tabindex="-1"></a>plt.plot(S_t,np.linspace(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">50</span>),color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb11-318"><a href="#cb11-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-319"><a href="#cb11-319" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-320"><a href="#cb11-320" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb11-321"><a href="#cb11-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-322"><a href="#cb11-322" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-323"><a href="#cb11-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-324"><a href="#cb11-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## Constructing An Expiration Graph</span></span>
<span id="cb11-325"><a href="#cb11-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-326"><a href="#cb11-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-327"><a href="#cb11-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-328"><a href="#cb11-328" aria-hidden="true" tabindex="-1"></a><span class="fu"># References</span></span>
<span id="cb11-329"><a href="#cb11-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-330"><a href="#cb11-330" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>*Option Pricing and Volatility - Advanced Strategies And Trading Techniques - Sheldon Natenberg.* </span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>